@baseUrl = http://localhost:3000/api
#Add user
POST {{baseUrl}}/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "fullname": "Isaias Elieser Osoria Tabares",
    "email": "admin@gmail.com",
    "password":"admin123",
    "role": "admin"
}

###
#Add estudiante
POST {{baseUrl}}/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "coret",
    "fullname": "Coret Osoria Tabares",
    "email": "coret@gmail.com",
    "password":"coret123",
    "role": "estudiante",
    "academicYear": 1,
    "group": "3106"
}

###
#Add profesor
POST {{baseUrl}}/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "coret",
    "fullname": "Coret Osoria Tabares",
    "email": "coret@gmail.com",
    "password":"coret123",
    "role": "estudiante",
    "academicYear": 1,
    "group": "3106"
}

###
#Get all user with pagination 
GET {{baseUrl}}/user?limit=2&page=2 HTTP/1.1

###
#Get user by id
GET {{baseUrl}}/user/3 HTTP/1.1

###
#Update user by id
PATCH {{baseUrl}}/user/1 HTTP/1.1
Content-Type: application/json

###
#Delete user by id
DELETE {{baseUrl}}/user/4 HTTP/1.1